# Generated by Django 2.1 on 2020-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.TextField(max_length=128)),
                ('firstName', models.TextField(max_length=128)),
                ('lastName', models.TextField(max_length=128)),
                ('dob', models.DateField()),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
        ),
    ]
